manipulator:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  # optional parameters for caching:
  max_cache_size: 10000
  min_pose_distance: 1
  min_joint_config_distance: 4
